### PR TITLE
Adding issue template

### PR DESCRIPTION
**Pull request by abhimeda**
Hello, this PR is introducing a new issue template for ROCm public repositories to make it easier for users to submit the details for issues and bugs. Problems pertaining to documentation or non-bug related, users have the ability to open a blank issue template to submit their report. 

Thank you,
Community Support Team (ML SW SDK)

### CODE REVIEW

**Comment by abhimeda** [comment]
Hey Sam, I saw your comments on the other PRs I've requested reviews for. I think my manager just wants to get the template our right now and any additions like MI300 will be made later

**Comment by abhimeda** [comment]
Hi, can this PR be reviewed?

**Comment by dmitrii-galantsev** [comment]
Hi, Apologies for the delay. I was on PTO.
Will get this added for amdsmi, rocmsmi, and RDC sometime this week.
Thank you.

**Comment by abhimeda** [comment]
> Hi, Apologies for the delay. I was on PTO. Will get this added for amdsmi, rocmsmi, and RDC sometime this week. Thank you.

Its okay! Happy new year. I hope you enjoyed your holidays! We've managed to figure out a way to load the issue template into the different repositories in ROCm without needing to create PRs. This way is actually more convenient because any subsequent changes (Eg. new version of ROCm is released) we can push a change that will be reflected across the entire organization

**Comment by dmitrii-galantsev** [comment]
Ohh, perfect! I will close the other 2 PRs as well then!
https://github.com/ROCm/rocm_smi_lib/pull/145
https://github.com/ROCm/rdc/pull/16

**Pull request closed without merging**
